---
- include_vars: "setup-details.yml"
- import_tasks: setup.yml
  when: IPTABLES == 'YES'
- import_tasks: iptables.yml
  when: IPTABLES == 'YES'
- import_tasks: iptablesaudit.yml
  when: IPTABLESAUDIT == 'YES'



